services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gymnet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - gymnet

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      FLASK_ENV: ${FLASK_ENV}
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - gymnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gymnet

networks:
  gymnet:

volumes:
  postgres_data: